# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopssonartestwithjava -Dsonar.projectKey=azuredevopswithjavakey -Dsonar.login=8c930426d95f71f9c5d06a34b9b032271219c94f
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipelines"
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'